#!/bin/bash
/show/description "Install mpd music player"
/system/install mpd
/system/install mpc
/show/listecho "Musics -> /user/musics" $OK
/system/makedir /opt/user/musics
/system/makedir /opt/user/musics/playlists
chown -R mpd:audio /opt/user/musics
cp /do/mpd/conf/default /etc/mpd.conf
/system/restart mpd
