#!/bin/bash
/show/description "Install mpd music player"
/system/install mpd
/system/install mpc
/show/listecho "Musics -> /opt/user/musics" $OK
/system/makedir /opt/user/musics
/system/makedir /opt/user/musics/playlists
chown -R mpd:audio /opt/user/musics
/system/downloadFile "mpdConf" "defaultPiGet" /etc/mpd.conf
/system/restart mpd
