#!/bin/bash
description "Install mpd music player"
installer mpd
installer mpc
description "Musics are saved inside /opt/user/musics"
mkdir /opt/user/musics
mkdir /opt/user/musics/playlists
chown -R mpd:audio /opt/user/musics
downloadFile "mpdConf" "defaultPiGet" /etc/mpd.conf
restarter mpd
