#!/bin/bash
if [ $# -eq 1 ]
then
	password=$1
	replaceLine "/etc/mpd.conf" "read,add,control,admin" "password                \"$password@read,add,control,admin\"" ""
	console
	cat /etc/mpd.conf
	console
	restarter mpd
else
	errorBox "Wrong arguments"
	usage "mpdPassword password"
	example "mpdPassword admin"
fi


