#!/bin/bash
if [ $# -eq 1 ]
then
	/show/listecho "Add password" $OK
	password=$1
	/string/replaceLine "/etc/mpd.conf" "read,add,control,admin" "password                \"$password@read,add,control,admin\"" ""
	# /show/file /etc/mpd.conf
	/system/restart mpd
else
	/show/errorBox "Wrong arguments"
	/show/usage "mpdPassword password"
	/show/example "mpdPassword admin"
fi


